---
title: "# The Phantom's Guide to learning R"
author: "Willie McRae"
date: "7th October 2017"
output: 
  html_document: 
    toc: yes
---
This is a document about my journey learning the programming language of R. 

It is written for people with little or no R experience and is designed to be a companion volume to more structured and dense texts that have been written by people who really **do** know lots of things about R.

I store my thoughts, notes and reviews on the many books, courses and events I have tried. 

I do not hold formal qualifications in computer science, data science or programming. However, I attempt to practice a scientific mindset, and many (in fact most) of my intellectual and philosophical heroes did not possess any of the qualifications I mentioned either!

This is my completely biased, subjective attempt to make some sense of the learning path I have been on.

If this inspires you and keeps you moving, then it has done the job intended.

Good luck!

> "Only a fool thinks that The Phantom cannot program in R"
(*Old Jungle Saying*)

# 0. Contents

1. Reasons for learning R
2. Online 
3. Books
4. Community and Events
5. Projects 
6. Tips and tricks
7. TLDR 

# 1. Reasons for learning R

For me, these are...

- Learn a programming language 
- Join a community of people who are learning and interested in making the world a better place through data analysis and data-driven decision making  
- Improve the output of my day to day activities around data analysis and data-driven decision making  

Not convinced? Try some of these links...  
[Why you should learn R first for Data Science](https://www.r-bloggers.com/why-you-should-learn-r-first-for-data-science/)


# 2. Online

There are many online courses and videos for the student of R. I will give you my thoughts on each that I have tried.

### 2.1 Interactive

Start here.  

[DataCamp](https://www.datacamp.com/) is completely worth the subscription fee and they also do Python courses.  
[Swirl](http://swirlstats.com/)


### 2.2 Websites

[r-bloggers](http://www.r-bloggers.com/how-to-learn-r-2/) is the first place you should go. There is a comprehensive R learning path which I refer to often. 

[Data Science Central](http://www.datasciencecentral.com/) for me is more of an inspirational site, with some good articles about Data Science in general.

Get all the [cheatsheets from R Studio](https://www.rstudio.com/resources/cheatsheets/).

[This tutorial](http://trevorstephens.com/kaggle-titanic-tutorial/getting-started-with-r/) by Trevor Stephens is very good! 

[Kaggle](https://www.kaggle.com/) is a good place to get inspired and look at useful scripts and approaches to real world data problems.

### 2.3 Video Courses

I find [Brandon Foltz's videos](https://www.youtube.com/user/BCFoltz) the best for learning and revising statistics, they are very thorough and simple to follow.  

Because I do not have a formal maths background, I am following the [Khan Academy](https://www.khanacademy.org/) maths program.  

### 2.4 MOOCs

I enrolled in the John Hopkins University Data Science Specialization and took the [R Programming](https://www.coursera.org/learn/r-programming) course only a few weeks after starting to learn R. Because of my non-programming background, I found it quite challenging and the teaching methods were not as effective as something like DataCamp. 

### 2.5 Cheatsheets

There are a numnbver of cheatsheets available online worth printing and having on hand - especially the ones from [R Studio](https://www.rstudio.com/resources/cheatsheets/)

# 3. Books

These are the books I have found to be most helpful. 

### 3.1 About R 

Advanced R  
Data Science With R  
R Cookbook  
Learning R  
R For Dummies

### 3.2 Other similar topics that helped me understand R

How To Lie With Statistics  
Visualize This  
Dynamic Documents with Knitr and Markdown  
Applied Predictive Modeling

# 4. Community and Events

Living in London, I am lucky to have access to a community of people with a similar interest in R and Data Science. 

### 4.1 Meetups

[London Kaggle Meetup](https://www.meetup.com/London-Kaggle-Meetup/)
[Central London Data Science Project Nights](https://www.meetup.com/central_london_data_science/), also has a location on [GitHub](https://github.com/central-ldn-data-sci)  
[LondonR](https://www.meetup.com/LondonR/)

### 4.2 Lectures

### 4.3 Events

[EARL Conference 2016](https://earlconf.com/london/) - [here are my notes](http://www.williemcrae.com/EARL_Conference_Notes_Master.html)  

# 5. Projects

# 6. Tips and Tricks

Reserved for bits and pieces of code, packages, and approaches that helped me. 

## 6.1 Notes on storytelling
 For every presentation first consider if it is a presentation or workshop   
 
 Presentations (to change minds and drive action) need a strong story  
 P.E.C  Point  Example (don’t create dissonance with the point)  
 Conclusion (action oriented)  10% what happened  90% diagnostics (why)  
 
 Workshops (for exploratory, informational) needs less story (the story is about the data collection, the reason we are solving a problem, looking at data etc)  
 1. Assessment of current state – hard truths  
 2. Future State  
 3. Gap Analysis  
 
Data storytelling is about showing the ‘tip of the iceberg’ and should be supported by a larger volume of research/exploration than the end consumer sees (but can be referred to quickly if required to add some kind of ‘re-assurance factor’ or ‘shock and awe’ depending on the audience)  

I believe some basics of communication are not really storytelling – these include things like clear explanations of what variables are, what the data set is, any calculated fields/exclusions, and also creation of plots, slides etc.  

### Pixar  

For the actual story bit I refer to the craft of writing/storytelling, rather than data specialists - check [this link]( http://io9.gizmodo.com/5916970/the-22-rules-of-storytelling-according-to-pixar)  

I find the following point very useful and keeps me on track when trying to craft a story (the trick is what changed, or will change and who it affected or will affect)  
Once upon a time there was ___. Every day, ___. One day ___. Because of that, ___. Because of that, ___. Until finally ___.  

### Questions approach vs scripted dialogue.  

From [Improv Wisdom](http://www.goodreads.com/book/show/182052.Improv_Wisdom)  

### Screenwriting  

Each scene has a beat, consider for your slides.  

## 6.2 Useful code

Use `mutate_each` from dplyr package to coerce multiple columns into different types  

I have created a simple [template for exploratory analysis](https://github.com/WillieMcRae/r_templates/blob/master/Rmd_exploratory_template.Rmd) which I use on brand new data sets


# 7. TLDR

I have found learning R to be a surprisingly fun, and extremely useful thing to do. It's tough, but rewarding. Do it!

> "The Phantom runs towards a challenge"
(*Old Jungle Saying*)


